export const transportistas = [																									
  {																									
    "byal_id": "BSKU",																									
    "Driver": "Betsi Samantha Kantun Uc",																									
    "ID Transportista": "A3O1H0MQI4P3UL",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																						
    "Numero Personal": 9991032338,																									
    "Numero Trabajo": 529993940561,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal12@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR1",																									
  },																									
  {																									
    "byal_id": "CGGE",																									
    "Driver": "Celia Georgina González Escalante",																									
    "ID Transportista": "A1PYP0KZBHTKUY",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9995826506,																									
    "Numero Trabajo": 529995826506,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.331@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR2",																									
  },																									
  {																									
    "byal_id": "DGMA",																									
    "Driver": "David Gregorio Montalvo Alonzo",																									
    "ID Transportista": "A3P1WHD654B6WG",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9991253905,																									
    "Numero Trabajo": 529991253905,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.315@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "DAMV",																									
    "Driver": "Didier Amaury Marfil vales",																									
    "ID Transportista": "A20BSQDCAZIVGE",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9994767456,																									
    "Numero Trabajo": 529901591949,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.328@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR3",																									
  },																									
  {																									
    "byal_id": "EFAJ",																									
    "Driver": "Eduardo Fernando Ávila Juárez",																									
    "ID Transportista": "A2U940JAYFEHT",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9993698509,																									
    "Numero Trabajo": 529995422394,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal49@gmail.com",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "GEMA",																									
    "Driver": "Genrry Eduardo Medina Andrade",																									
    "ID Transportista": "ANOWAYC8J7YWQ",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9844685417,																									
    "Numero Trabajo": 529994733811,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.293@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR6",																									
  },																									
  {																									
    "byal_id": "GMCP",																									
    "Driver": "Gustlaivi Michelle Carrera Polo",																									
    "ID Transportista": "A1BY6WDQM0E0SZ",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9992593426,																									
    "Numero Trabajo": 529994565780,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.305@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR7",																									
  },																									
  {																									
    "byal_id": "HGCA",																									
    "Driver": "Heidi Guadalupe Caamal Aguilar",																									
    "ID Transportista": "AKJIRFZIL3C3P",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9992253272,																									
    "Numero Trabajo": 529992253272,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal40@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR10",																									
  },																									
  {																									
    "byal_id": "HAGG",																									
    "Driver": "Henry Alberto González González",																									
    "ID Transportista": "A1CT1YY8I80CP9",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "2024-07-12T06:00:00.000Z",																									
    "Numero Personal": 9992723951,																									
    "Numero Trabajo": 529992723951,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.245@gmail.com",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "HAGG1",																									
    "Driver": "Henry Alberto González González1",																									
    "ID Transportista": "",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": "",																									
    "Numero Trabajo": "",																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "HAMA",																									
    "Driver": "Herbert Alejandro Marin ake",																									
    "ID Transportista": "A744QVJO94ZBQ",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9991083540,																									
    "Numero Trabajo": 529902437333,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "card.mid.bya.30@gmail.com",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "HABE",																									
    "Driver": "Hugo Andres Baas Ek",																									
    "ID Transportista": "A2CCOKJO3WMVHX",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9994555822,																									
    "Numero Trabajo": 529994576006,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.294@gmail.com",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "JDTG",																									
    "Driver": "Jairo Daniel Tuz Garcia",																									
    "ID Transportista": "A7V9LIIBPB986",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9991585382,																									
    "Numero Trabajo": 525646596869,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal05@gmail.com",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "JEGM",																									
    "Driver": "Jorge Eduardo Gómez Martín",																									
    "ID Transportista": "A30SY2CLF4UYTD",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9993901645,																									
    "Numero Trabajo": 529993901645,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.307@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR12",																									
  },																									
  {																									
    "byal_id": "JLCB",																									
    "Driver": "Jorge Luis Clavijo Boucourt",																									
    "ID Transportista": "A267Q8LSYJP1RG",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9995495475,																									
    "Numero Trabajo": 529995495475,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.32@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR15",																									
  },																									
  {																									
    "byal_id": "JLQC",																									
    "Driver": "Jose Luis Quijano Castillo",																									
    "ID Transportista": "AEMAC527LCDSQ",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "2024-07-12T06:00:00.000Z",																									
    "Numero Personal": 5628352356,																									
    "Numero Trabajo": 525642931299,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "mid.byal.238@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR16",																									
  },																									
  {																									
    "byal_id": "LECS",																									
    "Driver": "Luis Elmer Cosgaya Sandoval",																									
    "ID Transportista": "",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": "",																									
    "Numero Trabajo": "",																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR27",																									
  },																									
  {																									
    "byal_id": "MJCC",																									
    "Driver": "Maily Jocelin Carvajal Caamal",																									
    "ID Transportista": "ARYVJ4BVG378Q",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9992647927,																									
    "Numero Trabajo": 529993284842,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal37@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR20",																									
  },																									
  {																									
    "byal_id": "MFSL",																									
    "Driver": "Maria Fernanda Silva lozano",																									
    "ID Transportista": "A1SQN8RN1A6QUP",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9999499015,																									
    "Numero Trabajo": 529999499015,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal31@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR19",																									
  },																									
  {																									
    "byal_id": "MJLB",																									
    "Driver": "Maria Jose Losa bolio",																									
    "ID Transportista": "A2SBDLAJCZUFLZ",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9999038631,																									
    "Numero Trabajo": 525649615400,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal06@gmail.com",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "MABS",																									
    "Driver": "Miguel Angel Baas Sandoval",																									
    "ID Transportista": "A334OI0BZ5403G",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": 0,																									
    "Estacion": "ENCIERRO",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9994733811,																									
    "Numero Trabajo": 529994733811,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal02@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "RM024",																									
  },																									
  {																									
    "byal_id": "MAUO",																									
    "Driver": "Miguel Angel Uc Ortiz",																									
    "ID Transportista": "",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": "",																									
    "Numero Trabajo": "",																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "RJRS",																									
    "Driver": "Ricardo Jesus Rodriguez Sabatini",																									
    "ID Transportista": "",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": "",																									
    "Numero Trabajo": "",																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "RSQM",																									
    "Driver": "Rosa Sofia Quiñones Maldonado",																									
    "ID Transportista": "",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": "",																									
    "Numero Trabajo": "",																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "RRFC",																									
    "Driver": "Russell Rafael Franco Castillo",																									
    "ID Transportista": "A2REE82FZ6XXB1",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9992977416,																									
    "Numero Trabajo": 529992077416,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal33@gmail.com",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "RGG",																									
    "Driver": "Ruth Garcias Gomez",																									
    "ID Transportista": "",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": "",																									
    "Numero Trabajo": "",																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "",																									
    "Status": "INACTIVO",																									
    "Unidad": 0,																									
  },																									
  {																									
    "byal_id": "SAAZ",																									
    "Driver": "Salma Alejandra Andrade Zavala",																									
    "ID Transportista": "A1DP07T5HQLZSD",																									
    "Puesto": "Driver/Auto",																									
    "Operacion": "SAME_DAY",																									
    "Estacion": "DMY4",																									
    "Cumpleaños": "",																									
    "Numero Personal": 9995091892,																									
    "Numero Trabajo": 529995091892,																									
    "Direccion": "",																									
    "Ubicacion": "",																									
    "Email": "car.mid.byal28@gmail.com",																									
    "Status": "ACTIVO",																									
    "Unidad": "CAR24",																									
  }																									
]																		