export const UnidadesMid = [
  {
    "Unidad":"BLE001",
    "Placa":"CS6863A",
    "NIV":"JHHYEP0H0FK001405",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":218061,
    "Unidad de longitud":"km",
    "Marca":"Hino",
    "Modelo":"300 MODELO 616",
    "Año":2015,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"BLL002",
    "Placa":"YR1151D",
    "NIV":"VF3YDUMF0N2U55512",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"BLL003",
    "Placa":"YP2196D",
    "NIV":"JN6CE6CS3J9010014",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Nissan",
    "Modelo":"Urvan",
    "Año":2018,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"BLL004",
    "Placa":"G44BDV",
    "NIV":"WV1DLY7H7KH072228",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":85591,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"TRANSPORTER",
    "Año":2019,
    "Ciudad Origen":"CDMX",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"BLS002",
    "Placa":"YU2779D",
    "NIV":"WV1CAASE5HX002652",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":208492,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CADDY",
    "Año":2017,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"BLS018",
    "Placa":"YS1541C",
    "NIV":"WV1DAASKXPX004826",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":135655,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CADDY MAXI CARGO",
    "Año":2023,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"BLS029",
    "Placa":"YU9415D",
    "NIV":"VR3EUHNP8RJ541429",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":null,
    "Unidad de longitud":null,
    "Marca":"Peugeot",
    "Modelo":"PARTNER",
    "Año":2024,
    "Ciudad Origen":"MID",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR1",
    "Placa":"ZAB876E",
    "NIV":"LSGHD52H6LD080381",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Aveo",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":150239684200,
    "Poliza Desde":1697760000000,
    "Poliza Hasta":1729382400000,
    "Tarjeta Circulacion":"766903A",
    "TC Desde":1664755200000,
    "TC Hasta":1735603200000,
    "Liciencia":180021680,
    "Vigencia":1752883200000
  },
  {
    "Unidad":"CAR10",
    "Placa":"ZCS622C",
    "NIV":"MEX5G2607JT113293",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Partner",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR11",
    "Placa":"YXG309D",
    "NIV":"3G1MA5E27ML131496",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Onix",
    "Año":2021,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR12",
    "Placa":"YWM285F",
    "NIV":"LSGHD52H4KD070107",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Beat",
    "Año":2020,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR13",
    "Placa":"ZCH257C",
    "NIV":"MA6CB5CD1LT038309",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Beat",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR14",
    "Placa":"ZBU889E",
    "NIV":"3FADP4EJ8HM143993",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Ford",
    "Modelo":"Fiesta SE",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":"821418A",
    "TC Desde":1664409600000,
    "TC Hasta":1735603200000,
    "Liciencia":180032346,
    "Vigencia":1755129600000
  },
  {
    "Unidad":"CAR15",
    "Placa":"YZG132D",
    "NIV":"3KPA24BC2ME399830",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Kia",
    "Modelo":"Rio",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR16",
    "Placa":"ZCF311D",
    "NIV":"JS2FH81SXK6107953",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Zuzuki",
    "Modelo":"Ignis",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":150242858600,
    "Poliza Desde":1699660800000,
    "Poliza Hasta":1731283200000,
    "Tarjeta Circulacion":"637717A",
    "TC Desde":1645660800000,
    "TC Hasta":1735603200000,
    "Liciencia":10225540,
    "Vigencia":1755907200000
  },
  {
    "Unidad":"CAR17",
    "Placa":"ZBN809D",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Matiz",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR19",
    "Placa":"YXW900F",
    "NIV":"LVVDB21B9RC004444",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chirey",
    "Modelo":"Tiggo 4",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":"CHIIF0000005914",
    "Poliza Desde":1711497600000,
    "Poliza Hasta":1869264000000,
    "Tarjeta Circulacion":"1020425A",
    "TC Desde":1712102400000,
    "TC Hasta":1735603200000,
    "Liciencia":180041525,
    "Vigencia":1724457600000
  },
  {
    "Unidad":"CAR2",
    "Placa":"YZN577D",
    "NIV":"KL8PJ5C50FK044599",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Cruze",
    "Año":2015,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR20",
    "Placa":"YXU030E",
    "NIV":"3VW1K1AJ1HM265236",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Volkswagen",
    "Modelo":"Jetta",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":2030233936,
    "Poliza Desde":1704585600000,
    "Poliza Hasta":1735689600000,
    "Tarjeta Circulacion":"707588A",
    "TC Desde":1660176000000,
    "TC Hasta":1735603200000,
    "Liciencia":10268071,
    "Vigencia":1728864000000
  },
  {
    "Unidad":"CAR21",
    "Placa":"ZCX580C",
    "NIV":"MR2K29F31H1089875",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Toyota",
    "Modelo":"Yaris Hatchback",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR22",
    "Placa":"YWH362D",
    "NIV":"19XFC167XGE603910",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Honda",
    "Modelo":"Civic",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR23",
    "Placa":"ZBM244D",
    "NIV":"MA6CB6AD1HT041288",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Spark",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR24",
    "Placa":"UUL715K",
    "NIV":"3N1CK3CD2JL213594",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Beat",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR25",
    "Placa":"ZAP772E",
    "NIV":"VF3DD911P8JJ504809",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":301,
    "Año":0,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Externo",
    "Poliza":140288332901,
    "Poliza Desde":1697587200000,
    "Poliza Hasta":1729209600000,
    "Tarjeta Circulacion":"782096A",
    "TC Desde":1664496000000,
    "TC Hasta":1735603200000,
    "Liciencia":10209564,
    "Vigencia":1747353600000
  },
  {
    "Unidad":"CAR26",
    "Placa":"YZP368D",
    "NIV":"3G1TA5AF5FL157845",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":null,
    "Marca":"Chevrolet",
    "Modelo":"Aveo",
    "Año":2015,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR27",
    "Placa":"YWD402D",
    "NIV":"3N1CN7AD8HK453234",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Nissan",
    "Modelo":"Versa Drive",
    "Año":2017,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR28",
    "Placa":"ZBX776E",
    "NIV":"3G1TA5AF6HL245919",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Aveo",
    "Año":2017,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":0,
    "Poliza Desde":"00:00:00",
    "Poliza Hasta":"00:00:00",
    "Tarjeta Circulacion":0,
    "TC Desde":"00:00:00",
    "TC Hasta":"00:00:00",
    "Liciencia":0,
    "Vigencia":"00:00:00"
  },
  {
    "Unidad":"CAR29",
    "Placa":"USW992L",
    "NIV":"3VW2V49M1DM013153",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Volkswagen",
    "Modelo":"Jetta Sedan",
    "Año":2013,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR3",
    "Placa":"YXD473F",
    "NIV":"3N1CN7AD5JK398702",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Nissan",
    "Modelo":"Versa",
    "Año":2013,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR30",
    "Placa":"YWD537D",
    "NIV":"LSGHD52H1LD099047",
    "Estatus vehículo":"inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Aveo",
    "Año":2020,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR31",
    "Placa":"YWH886E",
    "NIV":"JS2FH81S9K6106504",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Susuki",
    "Modelo":"Ignis",
    "Año":2019,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR32",
    "Placa":"YWX974E",
    "NIV":"MALAN5BB1DM300403",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Dodge",
    "Modelo":"i10 GLS",
    "Año":2013,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR33",
    "Placa":"YYK376F",
    "NIV":"ML3ABW6J1RH007560",
    "Estatus vehículo":"inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Dodge",
    "Modelo":"Attitude",
    "Año":2024,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR4",
    "Placa":"ZBL966C",
    "NIV":"3KPA24AC3KE190269",
    "Estatus vehículo":"inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Kia",
    "Modelo":"Rio LX Sedan",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR5",
    "Placa":"ZAE333E",
    "NIV":"3N1CN7AD7JL809141",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Nissan",
    "Modelo":"Versa Advance",
    "Año":2018,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":"765991A",
    "TC Desde":1660780800000,
    "TC Hasta":1735603200000,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR6",
    "Placa":"YWN550F ",
    "NIV":"ML3ABT6J0NH003038",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Dedge",
    "Modelo":"Attitude",
    "Año":2022,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR7",
    "Placa":"YXS042F",
    "NIV":"LZWMLMGN9RF115835",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Groove",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"CAR8",
    "Placa":"ZCX632C",
    "NIV":"MA6CBSCD3KT010851",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MÉRIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Beat",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ExternoByal",
    "Poliza":150221641501,
    "Poliza Desde":1718928000000,
    "Poliza Hasta":1750464000000,
    "Tarjeta Circulacion":256152,
    "TC Desde":1704153600000,
    "TC Hasta":1735603200000,
    "Liciencia":10053375,
    "Vigencia":1752969600000
  },
  {
    "Unidad":"CAR9",
    "Placa":"YXM737E",
    "NIV":"MA6CB5CD7JT068394",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Chevrolet",
    "Modelo":"Beat",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV001",
    "Placa":"YT1782D",
    "NIV":"WV1DH22F7D7004704",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":210814,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CRAFTER",
    "Año":2018,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV002",
    "Placa":"YT9784D",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":157607,
    "Unidad de longitud":"km",
    "Marca":"NISSAN",
    "Modelo":"CABSTAR HD",
    "Año":2012,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV003",
    "Placa":"XV7450A",
    "NIV":"3N6AD35A3LK866751",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"NISSAN",
    "Modelo":"NP300",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV004",
    "Placa":"A674AH",
    "NIV":"VF3YDUMF0P2V59131",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":101614,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"MANAGER EXTRA LARGE",
    "Año":2023,
    "Ciudad Origen":"CIUDAD DE MEXICO",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV008",
    "Placa":"LF82042",
    "NIV":"VF3YDBTFXP2W12875",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":8345,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"MANAGER",
    "Año":2023,
    "Ciudad Origen":"CDMX",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV011",
    "Placa":"YU4708D",
    "NIV":"WV1GRNSY9P9064876",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":16861,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CRAFTER",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV012",
    "Placa":"YU4539D",
    "NIV":"WV1FHMSY3R9001655",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":32582,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CRAFTER",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV013",
    "Placa":"YU5843D",
    "NIV":"WV1GRNSYXP9060738",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":11815,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CRAFTER",
    "Año":2023,
    "Ciudad Origen":null,
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV016",
    "Placa":"YU7422D",
    "NIV":"VF3YDBTF5R2Y40902",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":10441,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"MANAGER",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV018",
    "Placa":"A-13893",
    "NIV":"JHHACR4H1NK506168",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":16370,
    "Unidad de longitud":"km",
    "Marca":"Hino",
    "Modelo":"300 - 514",
    "Año":2022,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"ELV026",
    "Placa":"YN3505E",
    "NIV":"VF3YDBTF0S2Z86422",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"MANAGER EXTRA LARGE",
    "Año":2025,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"GRS012",
    "Placa":"YS3378C",
    "NIV":"LZWNNNGM6PC819162",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":52681,
    "Unidad de longitud":"km",
    "Marca":"CHEVROLET",
    "Modelo":"TORNADO",
    "Año":2019,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"GERARDO",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LE001",
    "Placa":"LE31191",
    "NIV":"JAANPR75XN7000388",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":63105,
    "Unidad de longitud":"km",
    "Marca":"ISUZU",
    "Modelo":"ELF400",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LE002",
    "Placa":"LE84354",
    "NIV":"JAANPR755M7000247",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":43986,
    "Unidad de longitud":"km",
    "Marca":"ISUZU",
    "Modelo":"ELF 400",
    "Año":2021,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LE003",
    "Placa":"LE83285",
    "NIV":"JAANPR752M7000190",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":41125,
    "Unidad de longitud":"km",
    "Marca":"ISUZU",
    "Modelo":"ELF 400",
    "Año":2021,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV001",
    "Placa":"YWE667D",
    "NIV":"WV2DMW7H5JH193321",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":186870,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"Transporter",
    "Año":2018,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV004",
    "Placa":"YN3504E",
    "NIV":"VF3VLAHX9SZ001074",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2025,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV005",
    "Placa":"YN5284E",
    "NIV":"VF3YDBTF9S2Z15252",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2025,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV008",
    "Placa":"YT3217C",
    "NIV":"VF3VFAHX5MZ001826",
    "Estatus vehículo":"inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2021,
    "Ciudad Origen":" MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV010",
    "Placa":"YT6849C",
    "NIV":"VF3VFAHX3MZ008094",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":157979,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2021,
    "Ciudad Origen":"VILLAHERMOSA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV011",
    "Placa":"YT7013C",
    "NIV":"VF3VFAHXXMZ008092",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":152345,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2021,
    "Ciudad Origen":"CANCUN",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV016",
    "Placa":"YU6602C",
    "NIV":"VF3VFAHX6MZ005447",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":132944,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2021,
    "Ciudad Origen":"COATZACOALCOS",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV017",
    "Placa":"YT8227D",
    "NIV":"VF3JFAHX3NZ000451",
    "Estatus vehículo":"inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2021,
    "Ciudad Origen":"CANCUN",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV019",
    "Placa":"YU4866C",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2021,
    "Ciudad Origen":"CANCUN",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV024",
    "Placa":"WSM578B",
    "NIV":"VF3YDUMF8N2T57585",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"CANCUN",
    "Tipo propiedad":"BYAL",
    "Poliza":"05/02/2025, Solicita Carlos Saiden se deje porque mañana se envia a Cancun",
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV027",
    "Placa":"YP1831D",
    "NIV":"VF3YDUMF3N2U17790",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV029",
    "Placa":"YU9793C",
    "NIV":"VF3YDUMF7N2U17873",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":136778,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV032",
    "Placa":"YR1317D",
    "NIV":"VF3YDUMF6P2U46123",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2023,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV033",
    "Placa":"YR1432D",
    "NIV":"VF3YDUMF1N2U55244",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"VILLAHERMOSA",
    "Tipo propiedad":"BYAL",
    "Poliza":"En prestamos solo por mañana 06/02/2025, por la LV024",
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV035",
    "Placa":"YS1711C",
    "NIV":"WV2DLW7H5HH061396",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":151447,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"Transporter",
    "Año":2017,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV039",
    "Placa":"TM6852F",
    "NIV":"WV1DLY7H1FH060551",
    "Estatus vehículo":"inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Volkswagen",
    "Modelo":"Transporter",
    "Año":2015,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV043",
    "Placa":"TB4386L",
    "NIV":"VF3YDUMF8L2K78821",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2020,
    "Ciudad Origen":"CANCÚN",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV044",
    "Placa":"YS8687D",
    "NIV":"VF3YDBTF2R2W96399",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV046",
    "Placa":"YU3678D",
    "NIV":"VF3YDBTF4R2X79347",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV047",
    "Placa":"YU5366D",
    "NIV":"ZFCNFFCFXP2X89990",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Fiat",
    "Modelo":"Ducato",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV048",
    "Placa":"YU5919D",
    "NIV":"VF3VFAHX1RZ002303",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":25430,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV052",
    "Placa":"YU8029D",
    "NIV":"ZFCNFFCF1P2Y27736",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Fiat",
    "Modelo":"Ducato",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV053",
    "Placa":"YU5149D",
    "NIV":"VF3VFAHX9RZ000864",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV054",
    "Placa":"YU9397D",
    "NIV":"VF3FAHX8SZ000795",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":2168,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Expert",
    "Año":2025,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV055",
    "Placa":"YU9528D",
    "NIV":"VF3YDBTF3S2Z28921",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2025,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"LV057",
    "Placa":"YU9966D",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"M001",
    "Placa":"EHS1P",
    "NIV":"LBPKE124XJ0102458",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Cargo Biker",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Yamaha",
    "Modelo":"YBR125",
    "Año":2022,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"M002",
    "Placa":"51DKU3",
    "NIV":"LBPKE1247N0122320",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Cargo Biker",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Yamaha",
    "Modelo":"YBR125",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"M003",
    "Placa":"76DLC4",
    "NIV":"LBPKE1240N0121929",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Cargo Biker",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Yamaha",
    "Modelo":"YBR125",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"M005",
    "Placa":"17DHG1",
    "NIV":"ME1RG0929L2026176",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Cargo Biker",
    "Grupo":"MERIDA",
    "Odómetro":40221,
    "Unidad de longitud":"km",
    "Marca":"Yamaha",
    "Modelo":"SZ RR 149",
    "Año":2020,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"MIYABI",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"M006",
    "Placa":"78DLC4",
    "NIV":"LBPKE1246N0121983",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Cargo Biker",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Yamaha",
    "Modelo":"YBR125",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"M007",
    "Placa":"80DLC4",
    "NIV":"LBPKE1242N0121964",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Cargo Biker",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Yamaha",
    "Modelo":"YBR125",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"MAN01",
    "Placa":"2XA94D",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":null,
    "Unidad de longitud":null,
    "Marca":null,
    "Modelo":null,
    "Año":null,
    "Ciudad Origen":null,
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"MM001",
    "Placa":"71YWS3",
    "NIV":"3SPHAMZ32PA001549",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Cargo Biker",
    "Grupo":"MERIDA",
    "Odómetro":9831,
    "Unidad de longitud":"km",
    "Marca":"KINGWAY MX",
    "Modelo":"KW 200ZH 8",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"MTTO003",
    "Placa":"YN1169E",
    "NIV":"3C6LRVCG3PE595816",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"RAM",
    "Modelo":"2500 PROMASTER",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"MTTO005",
    "Placa":"YWP336D",
    "NIV":"3KPA35AC2KE214712",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":106603,
    "Unidad de longitud":"km",
    "Marca":"KIA",
    "Modelo":"Rio",
    "Año":2019,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"OPB004",
    "Placa":"ZBY408D",
    "NIV":"VF3DD9HP9NJ521625",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Peugeot",
    "Modelo":301,
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BYAL",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"OPB008",
    "Placa":"YYN917F",
    "NIV":"2T1BU4EEXBC676392",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Toyota",
    "Modelo":"Corolla",
    "Año":2011,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"OPB009",
    "Placa":"A-13860",
    "NIV":"5YFBU8HE5FP247718",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Toyota",
    "Modelo":"Corolla",
    "Año":2015,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"OPB010",
    "Placa":"A-13859",
    "NIV":"3VW1V49M4FM017891",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":380417,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"JETTA",
    "Año":2015,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"OPB011",
    "Placa":"A-13871",
    "NIV":"3VW1V49M0FM020495",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":342518,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"JETTA",
    "Año":2015,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"OPB012",
    "Placa":"A-13881",
    "NIV":"5YFBU8HE3FP244283",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":323841,
    "Unidad de longitud":"km",
    "Marca":"Toyota",
    "Modelo":"Corolla",
    "Año":2015,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"BAXIR",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"PALOMA",
    "Placa":"YT3111C",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":369368,
    "Unidad de longitud":"km",
    "Marca":"DODGE",
    "Modelo":"RAM",
    "Año":2002,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RC059",
    "Placa":"ULJ289H",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"NISSAN",
    "Modelo":"NV350 URVAN",
    "Año":2019,
    "Ciudad Origen":"CANCUN",
    "Tipo propiedad":"FLEX RENTING",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM004",
    "Placa":"YU0980D",
    "NIV":"WV2DLW7H7JH062457",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":329118,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"TRANSPORTER",
    "Año":2018,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM017",
    "Placa":"YU3702D",
    "NIV":"VF3YDUMF4N2U61975",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":70770,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM018",
    "Placa":"YU0873C",
    "NIV":"VF3YDUMF4N2S73621",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":105095,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM019",
    "Placa":"YR7155D",
    "NIV":"VF3YDUMF7N2T58002",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":107156,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"Manager Furgon",
    "Año":2022,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM022",
    "Placa":"ZCG041D",
    "NIV":null,
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"CARRO EXTERNO",
    "Grupo":"MERIDA",
    "Odómetro":115721,
    "Unidad de longitud":"km",
    "Marca":"SUZUKI",
    "Modelo":"IGNIS",
    "Año":2018,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM024",
    "Placa":"YYX368D",
    "NIV":"ML3AF56J6MH001700",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Mitsubichi",
    "Modelo":"Mirage",
    "Año":null,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Externo",
    "Poliza":"609-1001009667-1",
    "Poliza Desde":1615593600000,
    "Poliza Hasta":1773360000000,
    "Tarjeta Circulacion":32585,
    "TC Desde":1718236800000,
    "TC Hasta":1735603200000,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM025",
    "Placa":"YP2779D",
    "NIV":"VR3EF9HP7PJ520578",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":63921,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"PARTNER",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM026",
    "Placa":"ZAU656D",
    "NIV":"3VW1K1AJ6GM386410",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":113290,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"JETTA",
    "Año":2016,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM027",
    "Placa":"YR6731D",
    "NIV":"VF3VFAHX8RZ002654",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":10193,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"EXPERT",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM028",
    "Placa":"YYZ289D",
    "NIV":"3N1CN7AD1CL936065",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Auto",
    "Grupo":"MERIDA",
    "Odómetro":132989,
    "Unidad de longitud":"km",
    "Marca":"NISSAN",
    "Modelo":"VERSA",
    "Año":2012,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM029",
    "Placa":"YT5479D",
    "NIV":"VF3YDUMF4P2V59116",
    "Estatus vehículo":"inactivo",
    "Tipo vehículo":"Extra Large Van",
    "Grupo":"MERIDA",
    "Odómetro":102798,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"MANAGER",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM030",
    "Placa":"YU8706D",
    "NIV":"VF3YDBTFXR2Y46744",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":5148,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"MANAGER",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Arrendado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RM031",
    "Placa":"YU2389D",
    "NIV":"VF3YDBTF3R2Y43815",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"EXTRA LARGE VAN",
    "Grupo":"MERIDA",
    "Odómetro":4005,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"MANAGER",
    "Año":2024,
    "Ciudad Origen":"MPERIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RQ001",
    "Placa":"SW5154D",
    "NIV":"9535C3TC7NR017851",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":55745,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CHASIS MAN",
    "Año":2022,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RQ002",
    "Placa":"SW5183D",
    "NIV":"WF0ES4LY4NTH10470",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":106721,
    "Unidad de longitud":"km",
    "Marca":"FORD",
    "Modelo":"TRANSIT CHASIS",
    "Año":2021,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RQ003",
    "Placa":"SV7428C",
    "NIV":"WV3DLG7J4KX013695",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"3.5 TONELADAS",
    "Grupo":"MERIDA",
    "Odómetro":145950,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"TRANSPORTER",
    "Año":2019,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Rentado",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RRL001",
    "Placa":"YN3326E",
    "NIV":"LSCAB12EXRG188842",
    "Estatus vehículo":"Activo",
    "Tipo vehículo":"Large Van",
    "Grupo":"MERIDA",
    "Odómetro":0,
    "Unidad de longitud":0,
    "Marca":"Changan’an Motors",
    "Modelo":"NEW STAR TRUCK",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"ANYSA PEREZ CANTO",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RRS001",
    "Placa":"YN8471D",
    "NIV":"LZWNNNGMXPC831752",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":48990,
    "Unidad de longitud":"km",
    "Marca":"Chevrolet",
    "Modelo":"TORNADO",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"GONZALO",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RRS002",
    "Placa":"YR5373D",
    "NIV":"LZWNNNGMXPC826566",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"Small Van",
    "Grupo":"MERIDA",
    "Odómetro":47926,
    "Unidad de longitud":"km",
    "Marca":"Chevrolet",
    "Modelo":"TORNADO",
    "Año":2023,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"GONZALO",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"RRS003",
    "Placa":"TB3699M",
    "NIV":"LZWNNNGM0PC850830",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":63016,
    "Unidad de longitud":"km",
    "Marca":"Chevrolet",
    "Modelo":"TORNADO",
    "Año":2023,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"GONZALO",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"SV022",
    "Placa":"YU1409D",
    "NIV":"WV1DDASK0PX021464",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":115956,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CADDY MAXI",
    "Año":2023,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"SV023",
    "Placa":"YU1410D",
    "NIV":"WV1DDASK6PX018245",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":122441,
    "Unidad de longitud":"km",
    "Marca":"Volkswagen",
    "Modelo":"CADDY",
    "Año":2023,
    "Ciudad Origen":"MERIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"SV029",
    "Placa":"YU8204D",
    "NIV":"9BWKL45UXRP020978",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":null,
    "Unidad de longitud":null,
    "Marca":"Volkswagen",
    "Modelo":"SAVEIRO",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"SV030",
    "Placa":"YU8205D",
    "NIV":"9BWKL45U9RP022558",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":null,
    "Unidad de longitud":null,
    "Marca":"Volkswagen",
    "Modelo":"SAVEIRO",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"SV031",
    "Placa":"YU9398D",
    "NIV":"VR3EUHNP2RJ519135",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":10091,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"PARTNER",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"SV032",
    "Placa":"YU9399D",
    "NIV":"VR3EUHNP9RJ519150",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":10814,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"PARTNER",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  },
  {
    "Unidad":"SV033",
    "Placa":"YU9400D",
    "NIV":"VR3EUHNP1RJ541420",
    "Estatus vehículo":"Inactivo",
    "Tipo vehículo":"SMALL VAN",
    "Grupo":"MERIDA",
    "Odómetro":8139,
    "Unidad de longitud":"km",
    "Marca":"Peugeot",
    "Modelo":"PARTNER",
    "Año":2024,
    "Ciudad Origen":"MÉRIDA",
    "Tipo propiedad":"Propio",
    "Poliza":null,
    "Poliza Desde":null,
    "Poliza Hasta":null,
    "Tarjeta Circulacion":null,
    "TC Desde":null,
    "TC Hasta":null,
    "Liciencia":null,
    "Vigencia":null
  }
]